---
distro_alias: "LibreMesh"

# LibreMesh is based on OpenWrt, so use their ImageBuidlers
parent_distro: "openwrt"

# Use the following parent version
parent_version: "18.06.2"

latest: "testing"

versions:
  - "testing"
  - "master"
  - "aparcar"

active_targets:
  - apm821xx/nand
  - ar71xx/generic
  - ar71xx/mikrotik
  - ar71xx/nand
  - ar71xx/tiny
  - ath25/generic
  - ath79/generic
  - ath79/nand
  - ath79/tiny
  - bcm53xx/generic
  - brcm2708/bcm2708
  - brcm2708/bcm2709
  - brcm2708/bcm2710
  - brcm47xx/generic
  - brcm47xx/legacy
  - brcm47xx/mips74k
  - brcm63xx/generic
  - brcm63xx/smp
  - gemini/generic
  - ipq40xx/generic
  - ipq806x/generic
  - lantiq/xrx200
  - lantiq/xway
  - mcs814x/generic
  - mpc85xx/generic
  - mpc85xx/p1020
  - mvebu/cortexa53
  - mvebu/cortexa72
  - mvebu/cortexa9
  - octeon/generic
  - ramips/mt7620
  - ramips/mt7621
  - ramips/mt76x8
  - ramips/rt3883
  - ramips/rt305x
  - ramips/rt288x
  - sunxi/cortexa53
  - sunxi/cortexa7
  - sunxi/cortexa8
  - x86/64
  - x86/generic
  - x86/geode

# additional description to show in the user interfaces
distro_description: >
  LibreMesh is a modular framework for creating OpenWrt-based firmwares for
  wireless mesh nodes. Several communities around the world use LibreMesh as
  the foundation of their local mesh firmwares.

