---
asysup_common_pkg:
  - 'git'
  - 'subversion'
  - 'build-essential'
  - 'gawk'
  - 'ccache'
  - 'gettext'
  - 'wget'
  - 'unzip'
  - 'python'
  - 'postgresql'
  - 'odbc-postgresql'
  - 'python3-pyodbc'
  - 'python3-psycopg2'
  - 'python3-gnupg'
  - 'python-psycopg2'
  - 'python3-yaml'
  - 'libncurses5-dev'
  - 'zlib1g-dev'
  - 'libssl-dev'
  - 'xsltproc'
