---
distro_alias: "LibreMesh"

# LibreMesh is based on OpenWrt, so use their ImageBuidlers
parent_distro: "openwrt"

# Use the following parent version
parent_version: "18.06.2"

latest: "testing"

versions:
  - "testing"
  - "unstable"

active_targets:
  - ar71xx/generic
  - x86/64
  - ramips/mt7621

# additional description to show in the user interfaces
distro_description: >
  LibreMesh is a modular framework for creating OpenWrt-based firmwares for
  wireless mesh nodes. Several communities around the world use LibreMesh as the
  foundation of their local mesh firmwares.

